name: wolf_sdm
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - affine=2.4.0
  - appnope=0.1.4
  - asttokens=3.0.1
  - attrs=26.1.0
  - backports.zstd=1.3.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2026.2.25
  - certifi=2026.2.25
  - charset-normalizer=3.4.6
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - comm=0.2.3
  - cycler=0.12.1
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - folium=0.20.0
  - freetype=2.14.1
  - freexl=2.0.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geos=3.14.1
  - giflib=5.2.2
  - h2=4.3.0
  - hdf4=4.2.15
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=78.2
  - idna=3.11
  - ipykernel=7.2.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.3
  - json-c=0.18
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - krb5=1.22.2
  - lcms2=2.18
  - lerc=4.0.0
  - libaec=1.1.5
  - libarchive=3.8.5
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.18.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.4
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgdal-core=3.12.2
  - libgdal-hdf4=3.12.2
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.2
  - libkml=1.3.0
  - liblapack=3.11.0
  - liblzma=5.8.2
  - libnghttp2=1.67.1
  - libopenblas=0.3.30
  - libpng=1.6.55
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.51.2
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxml2-devel=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.2.1
  - minizip=4.0.10
  - munkres=1.1.4
  - muparser=2.3.5
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4
  - openjpeg=2.5.4
  - openssl=3.6.1
  - packaging=26.0
  - parso=0.8.6
  - patsy=1.0.2
  - pcre2=10.47
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=26.0.1
  - platformdirs=4.9.4
  - proj=9.7.1
  - prompt-toolkit=3.0.52
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - pyparsing=3.3.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2026.1.post1
  - qhull=2020.2
  - readline=8.3
  - requests=2.32.5
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=82.0.1
  - six=1.17.0
  - snappy=1.2.2
  - snuggs=1.4.7
  - sqlite=3.51.2
  - stack_data=0.6.3
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025c
  - uriparser=0.9.8
  - urllib3=2.6.3
  - wcwidth=0.6.0
  - wheel=0.46.3
  - xerces-c=3.3.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xyzservices=2025.11.0
  - zeromq=4.3.5
  - zlib=1.3.1
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
    - absl-py==2.4.0
    - aenum==3.1.17
    - aiobotocore==3.3.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aioitertools==0.13.0
    - aiosignal==1.4.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - backports-zstd==1.3.0
    - botocore==1.42.70
    - bounded-pool-executor==0.0.3
    - brotli==1.2.0
    - cattrs==26.1.0
    - cffi==2.0.0
    - contourpy==1.3.2
    - cryptography==46.0.5
    - dataclasses-json==0.6.7
    - debugpy==1.8.20
    - dill==0.4.1
    - earthaccess==0.16.0
    - earthengine-api==1.7.26
    - elevation==1.1.3
    - fasteners==0.20
    - flatbuffers==25.12.19
    - fonttools==4.61.1
    - frozenlist==1.8.0
    - fsspec==2026.2.0
    - gast==0.4.0
    - geojson-rewind==1.2.1
    - geomet==1.1.0
    - google-api-core==2.30.3
    - google-api-python-client==2.196.0
    - google-auth==2.49.1
    - google-auth-httplib2==0.4.0
    - google-auth-oauthlib==1.0.0
    - google-cloud-core==2.6.0
    - google-cloud-storage==3.10.1
    - google-crc32c==1.8.0
    - google-pasta==0.2.0
    - google-resumable-media==2.9.0
    - googleapis-common-protos==1.75.0
    - grpcio==1.78.0
    - h5py==3.16.0
    - httplib2==0.31.2
    - importlib-resources==6.5.2
    - jax==0.4.30
    - jaxlib==0.4.30
    - jmespath==1.1.0
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - keras==2.12.0
    - keras-tuner==1.4.8
    - kiwisolver==1.4.9
    - kt-legacy==1.0.5
    - libclang==18.1.1
    - markdown==3.10.2
    - markupsafe==3.0.3
    - marshmallow==3.26.2
    - matplotlib==3.10.8
    - ml-dtypes==0.5.4
    - multidict==6.7.1
    - multimethod==2.0.2
    - mypy-extensions==1.1.0
    - numpy==1.23.5
    - oauthlib==3.3.1
    - opt-einsum==3.4.0
    - pandas==2.3.3
    - pillow==12.1.1
    - pqdm==0.2.0
    - propcache==0.4.1
    - proto-plus==1.28.0
    - protobuf==4.25.8
    - psutil==7.2.2
    - pyasn1==0.6.3
    - pyasn1-modules==0.4.2
    - pycparser==3.0
    - pygbif==0.6.6
    - pyogrio==0.12.1
    - pypdf==6.18.1
    - pyproj==3.7.2
    - pystac==1.14.3
    - pystac-client==0.9.0
    - python-cmr==0.13.0
    - pyzmq==27.1.0
    - rasterio==1.4.4
    - referencing==0.37.0
    - requests-cache==1.3.1
    - requests-oauthlib==2.0.0
    - rpds-py==0.30.0
    - s3fs==2026.2.0
    - scikit-learn==1.7.2
    - scipy==1.15.2
    - sentinelhub==3.11.5
    - shapely==2.1.2
    - statsmodels==0.14.6
    - tenacity==9.1.4
    - tensorboard==2.12.3
    - tensorboard-data-server==0.7.2
    - tensorflow-estimator==2.12.0
    - tensorflow-io-gcs-filesystem==0.37.1
    - tensorflow-macos==2.12.0
    - tensorflow-metal==1.0.0
    - termcolor==3.3.0
    - tifffile==2026.3.3
    - tinynetrc==1.3.1
    - tomli==2.4.1
    - tomli-w==1.2.0
    - tornado==6.5.3
    - tqdm==4.67.3
    - typing-inspect==0.9.0
    - unicodedata2==17.0.1
    - uritemplate==4.2.0
    - url-normalize==2.2.1
    - utm==0.8.1
    - werkzeug==3.1.6
    - wrapt==1.14.2
    - yarl==1.23.0
